name: MERN CI

on:
  push:
   branches: [main]
   
jobs:
  mongo-init:

    runs-on: ubuntu-latest
    
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: action@setup-node@v3
        with:
          node-version: '18'

      - name: Waiting for MongoDB to be ready
        run: |
          until nc -z localhost 27017; do
            echo "Waiting for MongoDB..."
            sleep 2
          done
            echo "MongoDB is up"

      -  name: Seed MongoDB
         working-directory: ./backend
         run: |
          npm install   
          node seedTaskData.js
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: action@setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies for backend
        run: npm install
        
      - name: Running Backend Tests
        run: npm test  


